
export default {
  loading: false,
  dashboards: [],
  slices: [],
  datasources: [],
  sliceTree: {},
  users: [],
  usersDraft: [],
  compareInfo:{},
  user: {},
  dimensions: [],
  measures: [],
  measure: {},
  dimension: {},
  datasource: {},
  roles: [],
  permissions: [],
  subscribes: [],
  usergroups: [],
  originDimensions: [],
  originMeasures: [],
  tags: [],
  tagsLayer: [],
  dimensionLayer: [],
  pioProjects: [],
  operators: [],
  segmentExpands: [],
  projects: [],
  lossPredicts: [],
  pathAnalysis: [],
  pioCases: [],
  monitors: [],
  monitorAlarms: [],
  companys: [],
  tagTypes: [],
  tagGroups: [],
  tagTrees: [],
  dashboardsCategory: [],
  institutions: {},
  institutionsList: [],
  institutionsTree: [],
  businessDimension: {},
  targetCheck:{},
  resForAudit:{},
  institutionsChildren:[]
}
