export const Case_Data = [
  { id: '1', title: 'XXX用户运营大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-users-operate.png', type: '1' },
  { id: '11', title: 'XXX用户运营大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-users-operate2.png', type: '1' },
  { id: '20', title: 'XXX用户运营大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-users-operate3.png', type: '1' },
  { id: '21', title: 'XXX用户运营大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-users-operate4.png', type: '1' },
  { id: '22', title: 'XXX用户运营大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-users-operate5.png', type: '1' },
  { id: '7', title: 'XXX用户运营大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-users-operate6.png', type: '1' },
  { id: '25', title: 'XXX用户运营大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-users-operate7.png', type: '1' },
  { id: '2', title: 'XXX产品大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-product.png', type: '1' },
  { id: '3', title: 'XXX产品大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-product2.png', type: '1' },
  { id: '4', title: 'XXX产品大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-product3.png', type: '1' },
  { id: '5', title: 'XXX产品大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-product4.png', type: '1' },
  { id: '6', title: 'XXX产品大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-product5.png', type: '1' },
  { id: '8', title: 'XXX停车场数据大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-parking-overview.png', type: '1' },
  { id: '9', title: 'XXX铁路运营数据大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-railway.png', type: '1' },
  { id: '10', title: 'XXX铁路运营数据大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-railway2.png', type: '1' },
  { id: '12', title: 'XXX员工之声', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-employees.png', type: '2' },
  { id: '13', title: 'XXX顾客之声', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-customer.png', type: '2' },
  { id: '14', title: 'XXX顾客之声', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-customer2.png', type: '1' },
  { id: '15', title: 'XXX航空运营数据实时总览', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-aviation-overview.png', type: '1' },
  { id: '16', title: 'XXX航空运营数据实时总览', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-aviation-overview2.png', type: '1' },
  { id: '17', title: 'XXX航空运营数据实时总览', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-aviation-overview3.png', type: '1' },
  { id: '18', title: 'XXX航空航线飞机实时总览', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-aviation-overview4.png', type: '1' },
  { id: '19', title: 'XXX航空航线飞机实时总览', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-aviation-overview5.png', type: '1' },
  { id: '23', title: '工业投资行营分析', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-industrial-nvestment.png', type: '1' },
  { id: '24', title: 'XXX大数据中心', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-data-center.png', type: '1' },
  { id: '27', title: 'XXX日志监控', url: '/_bc/sugo-analytics-static/assets/images/livescreen/screen-log-monitoring.png', type: '1' },
  { id: '26', title: 'XXXAPP实时大屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/live-screen-xjw.png', type: '1' },
  { id: '28', title: 'XXX信息大屏-资讯屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/vert-faq.jpg', type: '2' },
  { id: '29', title: 'XXX信息大屏-反馈屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/vert-feedback.jpg', type: '2' },
  { id: '30', title: 'XXX信息大屏-销售屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/vert-selling.jpg', type: '2' },
  { id: '31', title: 'XXX信息大屏-回单屏', url: '/_bc/sugo-analytics-static/assets/images/livescreen/vert-resell.jpg', type: '2' },
  
  { id: '32', title: 'XXX大数据中心', url: '/_bc/sugo-analytics-static/assets/images/livescreen/light-green-323.jpg', type: '1' },
  { id: '33', title: 'XXX大数据中心-智慧学习网站', url: '/_bc/sugo-analytics-static/assets/images/livescreen/purple-433.jpg', type: '1' }
]
